spring.application.name=SIRA-Backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nombre_de_tu_base_sira}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true